import { chromium } from 'playwright'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } })
const page = await ctx.newPage()
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' })
await page.waitForTimeout(600)
await page.screenshot({ path: 'qa/be_hero_top.png' })
await page.evaluate(() => window.scrollTo(0, 850))
await page.waitForTimeout(700)
await page.screenshot({ path: 'qa/be_hero_mid.png' })
await ctx.close()
await browser.close()
console.log('done')
